### ISSUE TITLE
want to ask some qustion

### ISSUE THREAD

**Issue by bau720123** [jaypratapsingh/cordova_get_ip_address#1]
is it a wifi address => 192.168.X.X
or
network address => 1.2.3.4

**Comment by jaypratapsingh** [comment]
yes it is network address

**Comment by bau720123** [comment]
thanks @jaypratapsingh reply

[another question]
in the cordova io page，it said the bundle name is "com.jp.plugins"
http://plugins.cordova.io/#/package/com.jp.plugins
but...
in the git page，it said "com.jp.plugins.getipaddress"
https://github.com/jaypratapsingh/cordova_get_ip_address

so...which one is the correct ?
because I am using both PGB (build.phonegap.com) and Cordova Cli 5.0

**Comment by jaypratapsingh** [comment]
yes you can use "com.jp.plugins" okay.
