### ISSUE TITLE
a version confuse problem

### ISSUE THREAD

**Issue by bau720123** [jaypratapsingh/cordova_get_ip_address#3]
hi @jaypratapsingh 
just want to ask

for now I am using your plugin from "plugins.cordova.io"，at this page it said that the plugin can also install from npm
http://plugins.cordova.io/#/package/com.jp.plugins (1.0 version)
https://www.npmjs.com/package/com.jp.plugins.getipaddress (but strange 4.0 version)

but I found another plugin seem as same as the above
https://www.npmjs.com/package/com.jp.plugins (but strange 4.0 version)

because of according to this
http://phonegap.com/blog/2015/05/26/npm-plugins-available/
http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

so I want to change the install resource from "plugins.cordova.io" to "npm"
well...which one is the latest and usefull
https://www.npmjs.com/package/com.jp.plugins.getipaddress (but strange 4.0 version)
or
http://phonegap.com/blog/2015/05/26/npm-plugins-available/  (but strange 4.0 version)

**Comment by jaypratapsingh** [comment]
yes both are equal version, the difference of the version is because npm is not allow to reinstall the same version plugin so that i have version up on npm but everything is same on both side okay.

**Comment by bau720123** [comment]
thanks @jaypratapsingh 
I will use this one
https://www.npmjs.com/package/com.jp.plugins.getipaddress
